  
export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';
export const FILTER_BY_DATE = "FILTER_BY_DATE";
export const SORT_BY_DATE = "SORT_BY_DATE";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";